### ISSUE TITLE
Declaration of DeadBush\snowball\snow::onEnable(): void in phar://storage/emulated/0/Android/data/io.scer.pocketmine/files/PocketMine-MP/plugins/Snowball.phar/src/DeadBush/snowball/snow.php on line 16

### ISSUE THREAD

**Issue by Fanzho666** [deadbushmc/Snowball#2]
PocketMine-MP Crash Dump Sat Mar 5 11:14:04 UTC 2022

Error: Declaration of DeadBush\snowball\snow::onEnable() must be compatible with pocketmine\plugin\PluginBase::onEnable(): void
File: plugins/Snowball.phar/src/DeadBush/snowball/snow
Line: 16
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[7] use pocketmine\plugin\PluginBase;
[8] use pocketmine\event\Listener;
[9] use pocketmine\item\Item;
[10] use pocketmine\event\entity\EntityDamageByChildEntityEvent;
[11] use pocketmine\event\entity\EntityDamageEvent;
[12] use pocketmine\entity\projectile\Snowball;
[13] use pocketmine\utils\Config;
[14] 
[15] class snow extends PluginBase implements Listener {
[16]     public function onEnable(){
[17]         $this->saveDefaultConfig();
[18]         $this->getServer()->getPluginManager()->registerEvents($this, $this);
[19]     }
[20] 
[21]     public function onDamage(EntityDamageEvent $event) {
[22]         if($event instanceof EntityDamageByChildEntityEvent){
[23]             $child = $event->getChild();
[24]             $player = $event->getEntity();
[25]             if($child instanceof Snowball) {
[26]                 $mhealth = ($this->getConfig()->get("hearts"));

Backtrace:

PocketMine-MP version: 4.2.2 [Protocol 486]
Git commit: 12946fbe466335ccf9d94f63a65400903c924fca
uname -a: Linux localhost 4.9.190+ #1 SMP PREEMPT Sun Jan 9 16:58:51 CST 2022 aarch64
PHP Version: 8.0.12
Zend version: 4.0.12
OS: Linux, android
Composer libraries: 
- adhocore/json-comment 1.1.2@fc2f76979f0a44a5f5bc2a2b600d0762fe0e78e7
- brick/math 0.9.3@ca57d18f028f84f777b2168cd1911b0dee2343ae
- daverandom/callback-validator unknown@unknown
- fgrosse/phpasn1 v2.4.0@eef488991d53e58e60c9554b09b1201ca5ba9296
- netresearch/jsonmapper v4.0.0@8bbc021a8edb2e4a7ea2f8ad4fa9ec9dce2fcb8d
- pocketmine/bedrock-data 1.6.0+bedrock-1.18.10@e98c511584a7bd58a95986374d2df4b04c6a2ba0
- pocketmine/bedrock-protocol 8.0.0+bedrock-1.18.10@017e57c8f8a74118bcbba7332e7ebac9e6c81693
- pocketmine/binaryutils 0.2.4@5ac7eea91afbad8dc498f5ce34ce6297d5e6ea9a
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/classloader 0.2.0@49ea303993efdfb39cd302e2156d50aa78209e78
- pocketmine/color 0.2.0@09be6ea6d76f2e33d6813c39d29c22c46c17e1d2
- pocketmine/errorhandler 0.6.0@dae214a04348b911e8219ebf125ff1c5589cc878
- pocketmine/locale-data 2.4.3@4d0b081f1a79407e087968ea76aaf330db6ea2b5
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
- pocketmine/log-pthreads 0.4.0@61f709e8cf36bcc24e4efe02acded680a1ce23cd
- pocketmine/math 0.4.2@aacc3759a508a69dfa5bc4dfa770ab733c5c94bf
- pocketmine/nbt 0.3.2@3e0d9ef6b6c5fb45e3745a121296e75631b3eefe
- pocketmine/pocketmine-mp 4.2.2@12946fbe466335ccf9d94f63a65400903c924fca
- pocketmine/raklib 0.14.3@4798576fec0364266dce23b368a7fec5e5de7927
- pocketmine/raklib-ipc 0.1.1@922a6444b0c6c7daaa5aa5a832107e1ec4738aed
- pocketmine/snooze 0.3.1@0ac8fc2a781c419a1f64ebca4d5835028f59e29b
- ramsey/collection 1.2.2@cccc74ee5e328031b15640b51056ee8d3bb66c0a
- ramsey/uuid 4.2.3@fc9bb7fb5388691fd7373cd44dcb4d63bbcf24df
- rhumsaa/uuid unknown@unknown
- symfony/polyfill-ctype v1.24.0@30885182c981ab175d4d034db0f6f469898070ab
- symfony/polyfill-php80 v1.24.0@57b712b08eddb97c762a8caa32c84e037892d2e9
- symfony/polyfill-php81 v1.24.0@5de4ba2d41b15f9bd0e19b2ab9674135813ec98f
- webmozart/assert 1.10.0@6964c76c7804814a842473e0c8fd15bab0f18e25
- webmozart/path-util 2.3.0@d939f7edc24c9a1bb9c0dee5cb05d8e859490725

Loaded plugins:
AntiHunger 1.0.0 by NoobMCBG for API(s) 4.0.0
AntiVoid 1.2.0 by FiberglassCivic for API(s) 4.0.0
BasicSpawnProtection 1.0.0 by pmmp for API(s) 4.0.0
BedrockEconomy 2.0.7 by cooldogedev for API(s) 4.0.0
BetterFlight 1.0.0 by Electro for API(s) 4.0.0
BetterWarps 1.0.0 by Electro for API(s) 4.0.0
BloodInMC 1.0.0 by PedhotDev for API(s) 4.0.0
ChatCooldown 1.0.2 by Sergittos (@Sergittos) for API(s) 4.0.0
ClearLag 1.0.0 by tobias14 for API(s) 4.0.0
ComplexUpgradeUI 2.0.0 by  for API(s) 4.0.0
DataCleaning 1.0.0 by NhanAZ for API(s) 4.0.0
ErrorLog 1.0 by AkmalFairuz for API(s) 4.0.0
InventoryKeepChance 0.0.2 by JeroGamingYT for API(s) 4.0.0
KygekWhitelistKick 2.0.0 by Kygekraqmak, KygekTeam for API(s) 4.0.0
NBTEditor 1.0.0 by  for API(s) 4.0.0
NicknameColors 1.1 by ZhorifCraft451, MulkiAqi192 for API(s) 4.0.0
NoPVP 1.0.1 by Laith98Dev for API(s) 4.0.0
Nuke 1.0.0 by cheditx for API(s) 4.0.0
PiggyCustomEnchants 3.0.0 by DaPigGuy for API(s) 4.2.0
PlayerStatus 1.0.0 by Theslowaja for API(s) 4.0.0
PocKit 1.0.0 by  for API(s) 4.0.0
Rewards 5.0 by Wertzui123 for API(s) 4.0.0
ScoreHud 7.0.0 by Ifera for API(s) 4.0.0
SimpleFeed 2.0.0 by Electro for API(s) 4.0.0
TellRaw 2.0.0 by  for API(s) 4.0.0
VanillaX 3.0.0 by CLADevs for API(s) 4.0.0
VanishV2 3.1.0 by superbobby for API(s) 4.1.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNPIly3MaVv9JFpcrShjPEPcCkmKJEUjFjyuSKlOVNZkvVaDRmYOIyDpKjVP5933vduIZjS3a4
2WWpRKCP1+8+uhv8x0FcVBlvPt3Lqk6K/GDpHB40SSYPlqbneM7C9x1nbi0sz14cHrSl6rLm0OHa
QeDYXuAang+TUl4351VVVAfLv//34YFUj/84aLYlzDg4/3R69e764vL80/n791fvDw4PMlnXfI19
Z1KkvOINrM+KmJ1JHr1p681qVefFQ8jTVD0tl0V+nvMwlS9fsaytGxZKJoqshJnQyB6SZsPKQtzJ
JktyuVqVabtO8tXqmn6/4bUcg1iy+yKJAJE4SRELNbo+utGLzssNr47qShx1CB11+NADzExhGWTU
Pw/17E9Jfl+k9zKTeQMgo6SSojnoeqEFnkURSWTMAl7bWn4B4z/BDH/PSHkPS6xWl0ndyFxWOCzY
MyxpZLZaXcD/OMI0fhkS/Jc029XqnH6f8Qxk82Z7uknSSDWd4ziCYv42KMNEa99EPaOsip+AWSCL
1aoTAU2y90xqYVy9Wp0WeZysaZSjmGu68Bu0qa4ZyojJR2BPVLOBoSzJypQEVLOOe+wfONWDqQx+
yjZME8HiNhdKJXuVoWELPQx//tBsknr255rfyzMZ8zZtFEovXxFS/tOha9ncyAqs7eUrelGIveM5
MIraKrlGrCriWv2Sph2q2QpooIH+E14sQ5Ftmb+Iu5LByycCYX8gkb0i2i1rhGkSv1R9DMyh4bmQ
YJS/rhbEGcseASGSBQ5jx3opopdmKvZYzu74MuVbkMZkglpFz3B3ZiCqapERqp32aNK8nTm0UraR
PAV3ccxeDoLpZEcvL1cHMKZq6tXBK1gcTLypuJDKu2lfgWb8GvD7ts1BeviWc/SP48bDg961Hphz
Y25AC2+bTVHB9L8ffF8U4bvTN385AKi8TLDJoVHoQ0ntooNlzNNaHh5EskRlVijURdycjRsyTh6m
A7haDUiMn9FtFRyAHlxf3dx+vHp/eQZNDzKswVegNgGlOPoHdI5Tin5Q/nJMj7VLz9sklNUaDfA0
uU/Es5H1ppK82dzyuyRfp9s3Sc6rrSILsRqevkTepmnKenl0tIZg0YZzCB9H+0Af9fCAHeA2EnFT
8of8uioaSZY1Ys3e7i+Ivcyy8tl4g8BWq31orFbvcMhv5wmCPNpLGPJDRhU443NR5EW2HXNi2jHm
ASjKfDHlgSiKNCrWMpL3z8aKEUzgyASd3fffwZUR9KMdYMSWBvz22zRZb5oJU0bNX1CL8xS4XBXP
xg4ND0kfkJi+fY0/UOM/8qqsnxCmWv9v6SIcJi9fRVVaFNFF/u50TFPf9gWKrmW0KQC351PdkiCu
ViGikOSZAII0NpDziIrHXyWr0w2HQIZ6+jB2UpPmXdqsKW2QoIDSN0XNXp70z6+ejdC6A7laCcBK
aKwgnZvi+Futs0eV2JBC8L7k6zELuqYviLYpwoTXkFE+F8EdQKAXUUj5GmgdkPmtdN4SuJllGN5R
DwZJLjCzffxQriseyQ8XY9J3u3Zd85QFz0X4WVtc5KKtJKbqUwxWK/34NQEKqTvjDUdqc4jSI8om
zV/KtTY8f/2358u0CNxqNUbhdwdcjRsQSkX0ZTEmsm/aIXBK3uu7jKdveVK1n5+NxhFMKOo0GsPT
1wjuIsdcvqi230lZgonnQo5I29c7ptJ46p7+KqviLxwKwfV/3T4boWOgUDA/xerrJIsEf7ddy7uP
G2hIoZL7LhF3I3r3dP66LaoZFf854ziU3m4lz56N8hH81eopeqvVLra/VbV7lI/2EA/8+v7N7XmU
NMW4gBraft2mn4sJ70QIBgw5Yr/w6PFrhP49EIO4nxYpYTZQMu2YkmNORf03eEjiUwz1jot979r0
Lnn9c2IG1rPJewQTaJxg9/U6/n1x/cP1mEp635XVDnmXHJQi8J8zaRpAAi2Iw+92wCPkkL72buyl
6PUL0UVsJGjL47ORljSYHxHM1SoHBL5eOtfJer09beumyM5zyLHyZqyR+3rHtNlPaTvjMOkv7XZC
nPWvZAYa4Gq1B5u9jb9DpN0iR3vAHRGfaL/ppuFNO2HQuPkLUr/dyDotHvhP/NkETyARIu4DD5j8
BvEX4rtkXILqhn+PK72UWZEnP1/fgy2qhb8e8/fygVfRWBZdyxh3d1cIH2XVfG4T07KfTQgDyNVK
4/C7XcsA60iDIu27EUUlv23Hu2x905jcxVOtu4hl9XwKR9BWq27x4elrRHZD++lvpZzQMTR+Ibv5
X9sZGFD4evW7lWn6nj+MCOla/j31Uo+8XrZ/+Brkf4ACJE35jyPs+6YvuPfTy9cQ9+pnE4KGt1p1
CAxPX0tJvfnB2qGEmqaUPKmB6raUVViE4TRUmf/KdkUPUlGBaAxPX6YHDwd5BWQ0UuF4BHGo4mt5
JLM25Y2Mjoyj13lUFUl0FEEteZQU81rIaj6ceB3hGWV9dE0NuB00e3c9faPTSlh5NsuL2UPyGbwM
vdWyaaCoqeeK9lkk72dhm6RRfWzSAN3O8zqhd1HkdZHKeZM00NxAfggDkXd4koaMJ+98Cg4CqPMx
yUMeAN6T9zQJH7N03FIAZ+t60lSKKZD65xSYZo+bPgOg8XsoMt5sxi2CpyAyoH3ctmnzOzojtKiE
tCkTFdW2bArdQMP02fQwr60mCEZFhvZuGLZpWoE+Kk7yuBgPgrZGTpaPm3L8us4mrxteTwjAc6sI
xTVq+6kmBR/YKe9lGoUad0MxOJJxqthuaEPIwrqpaH9kmJoVVaMraZOozrbA5xyX00+sH3tzfTmV
T95M+EETknHL9dnVZEZUfKJBu41KtJOZm6nMyqJOHid8IfWuJ2OaTSU52qd2UIcHlQShoVquW8XD
jhfvgTvdUc0I6CYrJtJQYeLHdxPCk3VIp0DkY6y5B01NcSfz5PNU0DsqDq+I3pMxD1WyoyFbTjMt
AI6a+TkpVTkYzB10gOWm1FqG6oMn1DydpnOD4aNR8FoOFzgoMydbQTM/WFqG6wJJ9Sc8Z+k8X1kV
TSEKgOr4HqyB6eIB6LjjxaF0PM+2XSHiIAqc2LO55zqGERi2CCwnFhxgtxqVyyRvH1lagBVuirph
zjwAKow/shcmu3l3za7fn5+/u75lN23O/spzFjDTW7r+0jXZ6c0tswzLYpxXYuM5B0T3xPglqanT
i39TfirqblX0KfjCleukmxUZaJGsPoFxVLxKJLkqHm0KzGeO0KjAvWX6coaJ9nASCyteeMEiiA3u
ONyN3VBY3Ao9w4iMhWfF0pALX+LRVViBMzzS/scAQu0Twd1FZPqxYfmx78SLxSK0TM8XkRmYZmhE
Ulq2Y3NJHhIkBLjiMRJP05CLu9k9TxPwnLjzARy9y4uH/ET/Rjeyroq6lkdANq9zPOG/t+bAjBMp
Y8f3g8CMXFu6vvQMEbiuExpBaFqGCUiFPLACVNtcNpWsJXKY6M94WZIq3pMBnfhhKAzL5L6MQks6
fCG5Ffs8cmIeSBFEQlqxCP2IDLSPRqE6+5phtCJOenPjj10j8NWfm4Bl4AvXNF0foIaR6/PADXzP
XjiRFcWArCM84DM39oMeFJT04Sl4w1xIdyGA73zhmKYfijDkC9u25EICcwPpCd/0AnsHPNk1hQYS
IjD0xOViISUPTB6HPPIj4QR+7AppO0J6VrCIXOlBN59C2itErKrsE7w2tXBAqTwvFBx46vq+azmW
9F1h2cJyJXDG5dYOQDw0x1yC5IOoGSdOILlt2EFgyziKQzsQkW1Y0jJdL3INAO1bRgD6uQMJN3N6
GKAViL8XLbzYkrYdeb5pCzuIrEBYlnA8AZw0ox1s6P4WVMpRqtEBEZ9EHJZ2uOHYjh+ChkvfMgMZ
xqblxrEJNPmBEP4uOuQdZKcsqML2iRMZoeGbsckXgWMspOEvAs+XfOFxHtu2EYWAshW6u5DWhAsZ
gScC0xJGHIB/A1FHlm0avhRWZC6CMPBiBzQMMH0CYTaKIgqUZ8YLYKMvYhsEJixHOhLs3uIiksAt
g5tgBrbYMYLeEYC/PeFcCHvhBtw1fO4FUQw2KBz4tVgYPAS1FK4InDCegsjDpktHTmxpRIGMvdAT
bhw6rgRLcblpgVP25ML1bDO0wfDlFMLwOKMsg3z/yW9w5CNYFb9T2Ra4W5LRIvBdUBopDNtzLM9D
b2CHtgcWB42udCO5CKzFPiizpBQ6GJsngWVxz3HA5oUnFhHn3MV/vm2ZIHpTCmdh+1zu8LfOi+Kz
7PK3E4ODrYNrXvimcMyAm7HnSDAvB1yL7aIDdgNpBSHmBDyr5RbNYMgATGKMgJ+FIyVw1/IhqwvB
kBwjdE3D9aT0IzsMPU8YfADStkmk+WpDsAjCcBGHru37XmDG0cJegF44TiRCJ/JgtogtkDpO37RZ
zXk3/6l3r7dZXORbkGC6hRQynXXZ6D2gilppG+A1TN8SgW/y0Fy4ERiN7UShEYNye4Ef+AYq1z5Y
EDJ8YwTLXYQL0wKLk1EUBgsBgY374JpsS/iONOyFH1iRJYNfgmWOYUXSCbkVOci9OAgjQ5pBaHGw
OXDEtgveBSKHH6syKCugFGmOwLXJSkddjDte4DmAhVj4huODS/EdC5RAGiDjyITwBUSavrTcCZAS
LG6GvpvciI0OKbCDeCEjsFkBKhGGgcCg64rQcCMf/G3gBMYCwFAV1uvWfEvp1wuGGwNM0LWvVl9A
xRSfxUXFJlnWKn/BcF9Osq6gYrySrNlIVuSyhgfeMMHzvKBbqUku0hacBzzABLzuN4eABpG3gaQE
Yd0UmcS7rs1TmDWP5SEroKeqESQLwVvdsW3RVhoWS2KWFVESJ7QCJDd4zTTdIuDv5UMP7ihSdxJr
9lDk3zQMYz+vGJTLBTivBCPYFjHEC3CK7oeNzFlLB7MAYL7KV3kHbLnKGXvxcSMRMdYUsAqUDgCC
qZoDeADpTU0FreomVJXzZ8DPVDbEL0hDEyGZii3YkiFk4LiQs5RjHr+WS0Z5KnbUm7bBCwEzfV94
yVYH6gYlEylke9Eh+6noiNCL5lCsMryqvDogrF+nafHA8MwJEGX68h67Tzj7z1ZWWxzzMz7MdNcS
aGlp9Rfq6qeewwBnhrkkA2kCwxBauGWazTheV9N994iQFx/BmkBbgOc8ihikZUo0yHIss1kmed1W
dDWVAS2hRKSBcfLnlqfI0nVyD2Mh32gle6kXhRT6FUJXK8pZJUso+GYgkvVaVkvoprW/b7MQGAMa
97re5uKW13egFNUd6NicBnwATpLad5TisE1V5EULkoXh9SFOSCOm6hG0lUO6fQ2EYOFBvAFbxbas
zUG7cIgCfkOiB5pAA6viMQHtk8AGIIm0Ou+RQ95qhC5i1GMcg/p6yJLmG2BfU9G0SOJ1NFKnncns
JdCA14UtYguRMdOULgnUrh5zUo6qzfH8HrUT+F6SENQ+yZydyXv9zDK8MsVEBTX84dgwteIgR6qq
LRvVqhiGjIEqXGq6SLhgsFSIRMpYOF5FB7T3Y4A6gjoH1QBedJ+PFG3Yzuk1bZVnEpbbKoP9S1qE
oD24ucVUO9hBluDdXnhf83DbAMfZjWK1QcxNaoRN029Rag8JcZ40Cgz6YaYAdUpWE4VxAiiCt1I3
hwFMXEnZLamUHKTVogmzdQGCKtBSUStwoTWhOSPUlsxAKmB1cs8qW/t/TwHuFv4a/hteRf8a/nVT
lISC9nI9ShocuL+2KjHSRj1CuGqHlWlYjkaMnMBHsgqNX/3NM2BIdkEoocdgooXAlENgYvJRipac
b6FQVhaJgawfLR+FlFE9UKQc19Xt+ZLdfntxwy4v3l3cstfX15cX5zfs+vw9+3j1/rvz94cMBrHb
Kxh1zj5+e3V5zq7fX52e39zMd13AhB+W62l2XMsqKShYoyOukUCxkeSSiRu9szWB95AuRORbaMgM
XKFUbpZAnRY50AkOGrQJ6f0lZVNK9rDBqAs8QRekhhFkBQRc7+DIVUSiNa4whmAOQBPmT0ejLui9
bhBbKQWmCoqziK6Sq5rb0wDqJct6INU2NK31q/0oacptTfmaVyFYxmzIuskB7ecumRqio2cxPQt8
d8bzlhKTMSaQtLWgg68Ou5iwq4SdGqrwGkN50ih6s8EE5+xK+Xyl8JBZFG0a9bgkEEQecjbgXyvA
JaEPhHqGoWmF1d6Ss3gSJEl1FISetrgqsi7Yqtl6xGysmmMJIzVakk90g+1RqYl23HTJJIqsgpVQ
DbUiR21WqsxLpXdMd8ywo5PXGQ7SEwh3QrOjAN4gzIOx8z0MhqANgQ9WuAclq+tW1uqrrFquu0wU
nRauNmB12Amyy+EI/7nCBof+Ip8y/jijvf66w/2Ul9iaZG0GMRbCa4XA6csQFCTTX5gQFgNf0V40
K8linuoYJOKlxogWnGGG3ELQdXqJnRWqa1en1Wc4HXw1uDMhBUsPHFNGmcNMcLDPnrYzQIVyFUgf
kXuAnUowFJSSY73C1BxF4UAdTNP8VPR0K+PgIdtFBuKF0g7ur4P6NT1c5blsUGBLHSIgNdsUqUox
Q96IDWXihDJkTaBCOsiQb1NVke5VoUV/6ofJpgpvL8ZS6rrQrVbbBoEfspk5EiAJjxaeNR0yOgSQ
1x7yWDprwRQyUpRjnUOJPk6GRo3WnH0LuSB9rYTJHTu9/nAIcwGHEOzrIYlA7SlXUN6zhz8j+Evm
dWn3kJHXxJ3R2Dl7HYGj2vA0PoIyU5UJkQQd1kvBogy3DFHBRoY4hL0RsHEpcv6IXg1TTJ7OGSLx
4Tq/7pLtoTjEWgKRwksLOLEt83Km33eqm3fa6urks+zliWl5J8YaA55OmSBtV+oxCq1OYKlJr+bs
Ws9JebWmCVwXeFoXaMW44mskAWQCbKvLlDIWLD0zQB6NHT/fmrPTNKGv/bCWrqCYknXD3t1+IExr
IAnJDtuGYe1OohyWU8XFvPM1WdPOcNaSsB3XhzKn00X9BWt/Yb8nE2rjOE7EnFGU2nBMAvBLRA5x
AuaANOg7XHBTh4QLCI2+/4OhgrwuOWII0Zzcea1EqlIJGNtoHUVKpNo70K5OV1NnV5QknV3cvH4D
+RHlU21OOoQOu0VPSQeRKklIUBn1t6zRuN4Y6BzVG5EM2/Wyq9r+zEys1nTOugF/Rf1M1++12nFA
c6aDZpymTcJEYAptBe10U0CFj2bYFWuyK8fJjeOWMqv5fRcu8DvMmeqj7eZRHQ+I4fOhytr0hg1u
HKgdAWLVN+zHsHhE06/YxRl7+eOHi7NXIHiwe8ABxj+A3FAyCcR7sA4s4qpIM0jlH8CSYhBeDub+
45vLDr4u8EYt39BieJZGmQPJV+ciRFvRbR/pOPoI+M3wusNxEce0LPQl8Xb22CbRSCLE0Nl06+aW
9l6UsamPvhUTyNdry2prvQck8Js45Wj1nJmas2T6LBqXUUFEO0i9CkZBnq/7KiXHaeluMD7sRt0n
8mHWh+h922WKu6+zokX/Eatop90J8KzjLUZ39I+0GQLyx2cKzzD5PQXr0WQiPJeq+A6lAhbKGK2/
xg/eyJg2naKRbmHzNOwr8nGhnnzwgozvogq0CIpbTEJE3YelsR9NXgGkiPFO3wHZbjL+7rGxd/Z4
wrQQZMB1EqmogfRwkCloXN2GYy6sMYzCCBmp4EkvfXCjzSatHFwImUqqFZR+06ppcgdLYKVMvijl
QPq6Kh6ajfJksARnGwVt5ObA/OtGBWVCdobc6FCbDaxRpF2c1SO60FGj5BU0pk5VezL1plOX6NCc
iZAA3oxZ7AWgCcXyIMhhY6uX5fypMLX3euAJ1bMQTqDYU1pUFqW60EPSVS8Y8WmMDhy2hQtSIYRU
0koYc9F1QVKgSwxs0Vt5S53s4M4jldeqWeUKWrPww5PeR0eD10PLnOHfG9hp6h3DtFlfOxhFdfAH
M3WhsR+Jx/xLhcocvxKdJwVhDL5um2F5CKbc4E6rqAfUMVDpfjb0Ewnk5/h6Xcm13lTUO5BqowU/
ur7bpY/wA19zdXa1BH7oO0w6Q0D39SBVDcLByB9oxZoQHwigttENqzlE6p7zbYn3mZRwnjAVBKr6
tTJBLpR3t6ZGAecUd+7leDfvEKJDueFgFhJde4U4dJkphIxYVlB9zNAv5hgNVW8XvFTo4JPdQX3l
YxRtW8jCIbsh39q5MA2QpKz6uzWeSFXRNRZrk2RDBNHhGIHSZQ/QegwYKEV047ggbXvqSd0W93xY
QPeMV+g49+sBXwcTJUllAaPdJA2D0Z21+XjfaKMblYur+lpCewfchodyLaJEKIl7QHiC3lbqPAa9
TbeZojxvdzFuKHcgK+O1rtQgueZ4p0i/YQYEOGpZLTuhqT7QUdzVW7K/U+oCaeshbfP9NwJVgbkP
3uNzIiIDc+mKHDxupCjnhVolm71xlPwzFZA11QxUgIN8kjKVOgkYo6/WpXb1CBDRDBxDxdRhxSV7
e/n6VjVisSFxb+1P+r7GoRs8AkW5PLQfo6RqDsnp/kmneuq0ZbxtoYwYAx2wVu8q8lZrXQrCEls8
cGpF01ad3+1qtao/pyGnAnAgHAk6I6s7Ps26Mx5QAZXYv3hL3oSWovETIJQZ65ZPo5YZJZijzK9Q
2b98BN9W6zJX3NFt7/6P1CRQomxVJkfjkF76wxWpihTKVBSVBB8yo6p3x3g4uytUPMW8HkSs/oIF
neWtIGt5cQs8fCtDZjLDWFqLpWmxD7endO0K+7OiiY5XrWHwRXg7O8OKhT4+Uk0Vgdhzn/083X4v
mzfnwwPXG2YVnhciijO00GMzMG13p/Heo2YPm3VRkZTQCCYBLQ/4cdgMT+owwyUcoe7SOd6xZWDL
muOuQySP6U0dHPZtehbu8+J5UPde3pd6hSjBQgz0fntMPOjVuI+Kx9isMmjMzI/JBoY2NIPREDy1
Pz47f/v6w+XtiCY6T9RLUkxBA9fvk5z32MemSWJPwPVJ6LGE2Icw8hwSEdGXN5BIJlL9oaFag1UZ
atn/qYZjc8zkCnxbBxyf53hSAKRFx/9BP6Bf//wfLuOdrg==
===END CRASH DUMP===

**Comment by deadbushmc** [comment]
I have fixed your issue download the latest zip from github from here <a href="https://github.com/deadbushmc/Snowball">Click  Here</a>
or download the latest phar from here <a href="https://github.com/deadbushmc/Snowball/releases/tag/1.2">Click Here</a>
or wait for poggit to approve the build if you wanna download form poggit.
